version: '3.3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      SWAGGER_USER: 'swagger'
      SWAGGER_PASSWORD: 'swagger'
      MONGO_URL: 'mongodb://mongodb:mongodb@mongo/tracking'
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    volumes:
      - ./mongo-db:/data/db

