version: '3.3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      SWAGGER_USER: swagger
      SWAGGER_PASSWORD: swagger
      MONGO_URL: mongodb://db_mongo/tracking
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    container_name: db_mongo
    restart: always
    volumes:
      - ./mongo-db:/data/db

